version: "3.7"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  library:
    build: .
    container_name: library_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
    environment:
      DATABASE_URL: postgres://postgres@db
    depends_on:
      - db